### ISSUE TITLE
Unable to build extension

### ISSUE THREAD

**Issue by EvanKomp** [rvianello/chemicalite#9]
Upon `make`:

```
/chemicalite/src/mol.cpp:6:10: fatal error: GraphMol/MolPickler.h: No such file or directory
    6 | #include <GraphMol/MolPickler.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/chemicalite.dir/build.make:104: CMakeFiles/chemicalite.dir/mol.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/chemicalite.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

rdkit was installed via conda but building it from source did not resolve the issue.

Thanks for any help.

**Comment by rvianello** [comment]
Hi @EvanKomp 
unfortunately, the error message you shared is just not sufficient for me to suggest a solution. I guess something went probably wrong during the cmake configuration step, and the compiler is not provided the right path to the rdkit header files. You should probably carefully review the output from cmake, and then maybe try `make VERBOSE=1` which should output the full command line, and see if anything appears to be missing.

But before going into a probably long and nontrivial troubleshooting process, considering that you are installing rdkit with conda, are there any specific reasons for building chemicalite from the source code distribution? Chemicalite binary packages for linux and osx should be also already available from conda-forge.

In any case, as a general reference and starting point, and especially in case you are ok with building chemicalite inside a conda environment, you may want to look at the [recipe](https://github.com/conda-forge/chemicalite-feedstock/tree/main/recipe) that is used for building the packages for conda-forge.

**Comment by EvanKomp** [comment]
@rvianello Thanks for the reply.

I think your second point is particularly relevant. I am not quite sure why I had it in my head that `installation` and `build the extension` in the docs were mutually dependent, requiring both processes to get the functionality. A bit of ignorance.

If a successful `conda install -c conda-forge chemicalite` is all that is required, than all is well. 

Not going to try and debug the build. Thanks for the help!

**Comment by rvianello** [comment]
@EvanKomp no problem, I'm glad it only required a clarification.
